{
 "title": "NetApp FAS Monitoring",
 "time": { "from": "2022-04-01T00:00:00.000Z", "to": "2022-04-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Average Aggregate 1 Available Size",
   "type": "barchart",
   "description": "Rata-rata available size keseluruhan volume",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\navg(v_aggr_avail) as \"Available\"\nfrom fasalt.tifasaggr\nwhere\n--n_aggr ='Aggr2_8TB_N2'\nn_aggr ='Aggr1_4TB_N1'\nand\nto_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\ngroup by TO_CHAR(d_backup, 'Month')\norder by avg(v_aggr_avail) desc;"
    }
   ]
  },
  {
   "title": "Average Aggregate 2 Available Size",
   "type": "barchart",
   "description": "Rata-rata available size keseluruhan volume",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\navg(v_aggr_avail) as \"Available\"\nfrom fasalt.tifasaggr\nwhere\nn_aggr ='Aggr2_8TB_N2'\n--n_aggr ='Aggr1_4TB_N1'\nand\nto_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\ngroup by TO_CHAR(d_backup, 'Month')\norder by avg(v_aggr_avail) desc;"
    }
   ]
  },
  {
   "title": "Average Aggregate 1 Used Size",
   "type": "barchart",
   "description": "Rata-rata used size aggregate 1",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": " SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\n avg(v_aggr_used)::numeric(5,2) as \"Used (TB)\"\n from fasalt.tifasaggr\n where\n n_aggr = 'Aggr1_4TB_N1' \n and\n to_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\n  or to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\n   or to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\n    or to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\n     or to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\n      or to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\n       or to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\n        or to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\n --and n_vol ='vol_VMWDS_PROD_01_vol_mirror'\n group by TO_CHAR(d_backup, 'Month')\n order by avg(v_aggr_used) asc\n; "
    }
   ]
  },
  {
   "title": "Average Aggregate 2 Used Size",
   "type": "barchart",
   "description": "Rata-rata used size aggregate 2",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": " SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\n avg(v_aggr_used)::numeric(5,2) as \"Used (TB)\"\n from fasalt.tifasaggr\n where\n n_aggr = 'Aggr2_8TB_N2' \n and\n to_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\n  or to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\n   or to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\n    or to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\n     or to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\n      or to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\n       or to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\n        or to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\n --and n_vol ='vol_VMWDS_PROD_01_vol_mirror'\n group by TO_CHAR(d_backup, 'Month')\n order by avg(v_aggr_used) asc\n; "
    }
   ]
  },
  { "title": "Average Volume Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average Volume Available Size",
   "type": "barchart",
   "description": "Rata-rata available size keseluruhan volume",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\navg(v_vol_avail) as \"Available\"\nfrom fasalt.tifasvol\nwhere\nto_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\nor to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\ngroup by TO_CHAR(d_backup, 'Month')\norder by avg(v_vol_avail) desc;"
    }
   ]
  },
  {
   "title": "Average Volume Used Size",
   "type": "barchart",
   "description": "Rata-rata used size keseluruhan volume",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": " SELECT TO_CHAR(d_backup, 'Month') AS \"Month\",\n avg(v_vol_used)::numeric(5,2) as \"Used (TB)\"\n from fasalt.tifasvol\n where \n to_char(d_backup, 'YYYY-MM-DD') like '2022-03%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-04%'\n or to_char(d_backup, 'YYYY-MM-DD') like '2022-05%'\n  or to_char(d_backup, 'YYYY-MM-DD') like '2022-06%'\n   or to_char(d_backup, 'YYYY-MM-DD') like '2022-07%'\n    or to_char(d_backup, 'YYYY-MM-DD') like '2022-08%'\n     or to_char(d_backup, 'YYYY-MM-DD') like '2022-09%'\n      or to_char(d_backup, 'YYYY-MM-DD') like '2022-10%'\n       or to_char(d_backup, 'YYYY-MM-DD') like '2022-11%'\n        or to_char(d_backup, 'YYYY-MM-DD') like '2022-12%'\n --and n_vol ='vol_VMWDS_PROD_01_vol_mirror'\n group by TO_CHAR(d_backup, 'Month')\n order by avg(v_vol_used) asc\n; "
    }
   ]
  },
  { "title": "Volume Total Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Volume 1 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_01_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_02_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_03_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_04_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_05_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Total Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_total as \"Total (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_06_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  { "title": "Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Aggregate 1 Available Size",
   "type": "timeseries",
   "description": "Semakin besar semakin bagus",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_aggr_avail as \"Available Size (TB)\"\nFROM\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate 2 Available Size",
   "type": "timeseries",
   "description": "Semakin besar semakin bagus",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_aggr_avail as \"Available Size (TB)\"\nFROM\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate 1 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "select \nd_backup, v_aggr_used as \"Used Size (TB)\"\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate 2 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "select \nd_backup, v_aggr_used as \"Used Size (TB)\"\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate 1 Used Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "select \nd_backup, p_aggr_used as \"Used (%)\"\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate 2 Used Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "rawSql": "select \nd_backup, p_aggr_used as \"Used (%)\"\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  },
  { "title": "Volume Available Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Volume 1 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_01_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_02_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_03_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_04_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_05_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Available Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as \"Size Available (GB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_06_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  { "title": "Volume Used Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Volume 1 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'vol_VMWDS_PROD_01_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'vol_VMWDS_PROD_02_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_03_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_04_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_05_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Used Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
   "targets": [
    {
     "rawSql": "select\nd_backup, v_vol_used as \"Used (TB)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_06_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  { "title": "Volume Used Percentage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Volume 1 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 1",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'vol_VMWDS_PROD_01_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 2",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 78 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'vol_VMWDS_PROD_02_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 3",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 78 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_03_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 4",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_04_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 5",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 84 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_05_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Used Percentage",
   "type": "timeseries",
   "description": "Persentase penggunaan Volume 6",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 84 },
   "targets": [
    {
     "rawSql": "select\nd_backup, p_vol_used as \"Used (%)\"\nfrom\nfasalt.tifasvol\nwhere\nn_vol = 'VMWDS_PROD_06_vol_mirror'\norder by\nd_backup;"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Volume 1 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='vol_VMWDS_PROD_01_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='vol_VMWDS_PROD_02_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='VMWDS_PROD_03_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='VMWDS_PROD_04_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='VMWDS_PROD_05_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Snapshot Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_sc_daily as \"Daily (GB)\", v_sc_weekly as \"Weekly (GB)\", v_sc_monthly as \"Monthly (GB)\"\nFROM fasalt.tifassc\nWHERE\n n_vol ='VMWDS_PROD_06_vol_mirror'\nORDER BY d_backup;"
    }
   ]
  }
 ]
}