{
 "title": "NetApp FAS Monitoring",
 "time": { "from": "2022-04-01T00:00:00.000Z", "to": "2022-04-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Volume 1 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol1\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_01_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 2 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol2\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='vol_VMWDS_PROD_02_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 3 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol3\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_03_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 4 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol4\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_04_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 5 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol5\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_05_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Volume 6 Available Size April 2022",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_vol_avail as Vol6\nfrom\nfasalt.tifasvol\nwhere\nn_vol ='VMWDS_PROD_06_vol_mirror'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate Available April 2022",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\nd_backup, v_aggr_avail as aggregate1\nFROM\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    },
    {
     "rawSql": "SELECT\nd_backup, v_aggr_avail as aggregate2\nFROM\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Aggregate Used April 2022",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "select \nd_backup, v_aggr_used as aggregate1\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    },
    {
     "rawSql": "select \nd_backup, v_aggr_used as aggregate2\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  },
  {
   "title": "Persentase Aggregate Used April 2022",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "select \nd_backup, p_aggr_used as aggregate1\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr1_4TB_N1'\norder by d_backup;"
    },
    {
     "rawSql": "select \nd_backup, p_aggr_used as aggregate2\nfrom\nfasalt.tifasaggr\nwhere n_aggr ='Aggr2_8TB_N2'\norder by d_backup;"
    }
   ]
  }
 ]
}